library(ggplot2)
library(RColorBrewer)
library(gdata)
library(gtools) 
library(RgoogleMaps)
library(ggmap)   
library(plyr)
library(dplyr)
library(car)
library(reports)
library(tidyr)
library(reshape2)

library(sp)
library(rgeos)
library(rgdal)
library(dismo)
library(SDMTools)  

library(ellipse)  
library(grid)
print("loaded from PaperZero .Rprofile")

#install.packages("ellipse")
#remove.packages("sp")

#.libPaths()
